-
  name: Install Nginx and Deploy Website on Localhost
  host: prod
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest

    - name: Starting Nginx
      service:
        name: nginx
        state: started
        enabled: yes 

    - name: Deploying Website
      copy:
        src: index.html
        dest: /var/www/html       