-
  name: Nginx Playbook
  hosts: servers
  becomes: yes
  tasks:
    - name: Update the System
      command: apt update
    
    - name: Install Nginx
      apt:
        name: Nginx
        state: latest

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes